### ISSUE TITLE
Add shared profile for Carthage support

### ISSUE THREAD

**Issue by robertoschwald** [pixelglow/ZipZap#100]
e.g. like in remaerd/zipzap

**Comment by pixelglow** [comment]
I like Carthage and it's a lot simpler than CocoaPods, so it's worthwhile doing the integration. Is the essential point the need to create dylibs/frameworks instead of static libraries? I looked at *ramaerd/zipzap* and the intent for those changes don't look obvious to me.

**Comment by robertoschwald** [comment]
AFAIK you need to commit shared Xcode schemes (tick the "share" checkbox and commit).

To test it, install Carthage, then create a test directory, add a Cartfile file with your library defined and call
    carthage build --no-skip-current

**Comment by remaerd** [comment]
Hello.
I accidentally find out that you guys leaving message on the Carthage issue page. I don't know how @robertoschwald find out my fork. But I'm really glad to provides help.

It's quite simple actually.
1. You have to add two targets in your project. An iOS framework and an OS X framework. And make them both 'Shared'.
2. There's a naming issue when building framework. You can't create frameworks with a name like 'zipzap-ios' or 'zipzap-osx'. Instead, you should rename your iOS and OS X target in 'Build Settings - Product Name' to 'zipzap'.

That's all I have done to my fork. I hope it can be helpful.
Thank you for your framework!
