### ISSUE TITLE
ZZArchiveEntry returns 'nil' fileName with zips from different regions

### ISSUE THREAD

**Issue by rickyproy** [pixelglow/ZipZap#102]
So I love this framework and use it often!

But I just had a bug filed because a user created a zip on a japanese windows machine and the zip zap framework is unable to get the filename. its returns as nil. I believe it has to do with the string encoding.

can you guys try this file i've attached and see if we can work together to come up with a solution?

thanks guys!

https://www.dropbox.com/s/46231uyuly8wkhb/CRM-Attachment_%E3%83%8B%E3%83%A5%E3%83%BC%E3%82%AB%E3%83%AC%E3%83%89%E3%83%8B%E3%82%A2.zip?dl=0

**Comment by pixelglow** [comment]
Use the `initWithURL:options:error:` initialiser and pass in `NSShiftJISStringEncoding` as the encoding e.g.

```
ZZArchive* archive = [[ZZArchive alloc] initWithURL:fileURL
                                            options:@{ ZZOpenOptionsEncodingKey : @(NSShiftJISStringEncoding)}
                                              error:&err];
```

The zip file you linked is actually incorrectly written -- filenames should either be CP437 or UTF-8, depending on a bit set in the file entry. However many tools just write out the filename in whatever encoding they choose, and it's up to us client programs to specify externally what the encoding actually is. See: http://stackoverflow.com/questions/13261347/correctly-decoding-zip-entry-file-names-cp437-utf-8-or
