### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by sverin** [pixelglow/ZipZap#104]
When I build and include the framework or static library I got this issue:

Undefined symbols for architecture x86_64: "_OBJC_CLASS_$_ZZArchive"

I saw another issue about this , https://github.com/pixelglow/ZipZap/issues/66

I tried the suggestion there, but it still doesn't work. What I'm doing wrong.
Never seen this before for any framework I used.

**Comment by iToto** [comment]
You have to build two different binaries for `libZipZap.a` when using this lib with the simulator/hardware as one uses 64bit and the other 32. You can simply interchange them when running against the different architectures.

**Comment by sverin** [comment]
The build for OS X uses the x86_64 architecture while the build for iOS uses the arm64, right ?
However, even if build either framework or static library for iOS (arm64), I get the error about x86_64 when I include it in my project.

**Comment by pixelglow** [comment]
@sverin, can you tell me a little more about your set up? Are you using the zipped source library, git submodule, CocoaPods or Carthage to integrate? Can you send me a minimal project that shows the error e.g. by DropBox?

**Comment by sverin** [comment]
I used the zipped source library. I deleted the project and did a new build from scratch, and now it's working. I dont know what was wrong with my first try.
