### ISSUE TITLE
Can not produce static library for ios

### ISSUE THREAD

**Issue by kscorpio** [pixelglow/ZipZap#107]
1 when i select the target ios and build  ，can not build a static library

 only change to target mac ,can be build library successfully,

2 but when drag the library to project which is arm 64, arm v7

it build with error`libzipzap.a, file was built for archive which is not the architecture being linked (arm64):  ....`

**Comment by pixelglow** [comment]
When you select `ZipZap (iOS Static Library)`, it should build an iOS version of `libZipZap.a` within your `Products/Debug-iphoneos` or `Products/Release-iphoneos`. The archive files listed on the Xcode project navigator are Mac OS X only.

Are you using the project by itself, `git submodules`, Carthage or CocoaPods to integrate?

**Comment by pixelglow** [comment]
No further response?
