### ISSUE TITLE
Unresolved identifier `ZZInflateInputStream`

### ISSUE THREAD

**Issue by RLovelett** [pixelglow/ZipZap#110]
When using ZipZap in a Swift (2 if it matters) project I am unable to reference `ZZInflateInputStream`. It fails to compile with the error: `Use of unresolved identifier 'ZZInflateInputStream'`. I thought I had everything configured properly because I could reach and use both `ZZArchive` and `ZZArchiveEntry`.

Any pointers?

**Comment by pixelglow** [comment]
At the moment, `ZZInflateInputStream` is not a public header; you would generally use inflate + deflate through `ZZArchiveEntry` init params. We probably need to refine it a little more for public consumption, at the very least we would need a proper set of unit tests around it.
