### ISSUE TITLE
Swift 2.0 - Cannot Invoke Initializer ZZArchive

### ISSUE THREAD

**Issue by Gerst20051** [pixelglow/ZipZap#112]
![screen shot 2015-09-23 at 12 26 29 pm](https://cloud.githubusercontent.com/assets/235372/10051260/aa58459e-61ee-11e5-93d6-e7b465b2c340.png)

Cannot invoke initializer for type 'ZZArchive' with an argument list of type '(URL: NSURL, options: [String: Bool], error: NilLiteralConvertable)'

**Comment by cLarnhof** [comment]
The options parameter expects a NSNumber, no a Bool. Try replacing 'true' with 'NSNumber(bool: true)'
