### ISSUE TITLE
Some files aren't written a Copyright notice.

### ISSUE THREAD

**Issue by Shinproxy** [pixelglow/ZipZap#116]
I found some files which don't write a Copyright notice.
Could you fix it?
 
ZZAESDecryptInputStream.h
ZZAESDecryptInputStream.mm
ZZChannel.h
ZZChannelOutput.h
ZZConstants.h
ZZConstants.m
ZZDataChannel.h
ZZDataChannel.m
ZZDataChannelOutput.h
ZZDataChannelOutput.m
ZZDataProvider.h
ZZError.m
ZZFileChannel.h
ZZFileChannel.m
ZZFileChannelOutput.h
ZZFileChannelOutput.m
ZZScopeGuard.h
ZZStandardCryptoEngine.cpp
ZZStandardCryptoEngine.h
ZZStandardDecryptInputStream.h
ZZStandardDecryptInputStream.mm

**Comment by pixelglow** [comment]
@danielgindi some of these files were created by you. Would it be OK if you assigned copyright to Pixelglow Software?

ZZAESDecryptInputStream.h
ZZAESDecryptInputStream.mm
ZZConstants.h
ZZStandardCryptoEngine.h
ZZStandardCryptoEngine.cpp
ZZStandardDecryptInputStream.h
ZZStandardDecryptInputStream.mm

**Comment by danielgindi** [comment]
Yeah NP!

**Comment by Shinproxy** [comment]
I appreciate your quick response on this issue.
