### ISSUE TITLE
Asking for help.

### ISSUE THREAD

**Issue by remaerd** [pixelglow/ZipZap#121]
Hello, This is not a ZipZap problem but I need help to make an Objective-C dynamic framework work with Swift.

I'm trying to use the https://github.com/Kentzo/ShortcutRecorder Framework with Swift 2.1 + Carthage. Carthage do built the framework nicely. But when I try to use it with Swift. I cannot import the framework and use it in Swift. And I have no idea how to solve the problem.

I knew that you have the experience to make ZipZap working with Swift and Carthage. So I write down this issue to ask for help to make ShortcutRecorder available at Swift.

Thank you.

**Comment by pixelglow** [comment]
Since the ShortcutRecorder framework is unrelated to ZipZap and is a non-trivial implementation, it would fall under my consult work. Email me *glen dot low at pixelglow dot com* to continue this conversation.
