### ISSUE TITLE
Usage with Swift

### ISSUE THREAD

**Issue by gobozgz** [pixelglow/ZipZap#122]
Hi,

I suppose It's no t a bug, but I'm trying to uncompress a downloaded file in aplication's document folder but I don't find anyway of do it.

I've take the recipe in https://github.com/pixelglow/ZipZap/wiki/Recipes named "Unzip an existing zip file to the file system" and I've tried to translate to Swift 2.0 for Xcode 7 but I think i'm doing something wrong cause I don't know Objetive C. Please, can anyone help me?. I also think It would be a great Idea adding swift recipes to the wiki.

Thanks a lot to everybody.

David

**Comment by RLovelett** [comment]
Can you provide a little bit more about what is going wrong?
