### ISSUE TITLE
ZZEndOfCentralDirectoryReadErrorCode Error

### ISSUE THREAD

**Issue by josh-fuggle** [pixelglow/ZipZap#138]
Hello,

My name is Josh and I have been using your library for some time. Firstly, I would like to say that it is fantastic.

Recently, I have had error reports from users, which I have worked this out to be something going wrong with our zipping code. Specifically, I am getting an `ZZEndOfCentralDirectoryReadErrorCode` from the ZipZap library.

I was wondering if you could explain what an `End of Central Directory Read` error is and in what circumstances it can occur.

Thanks in advance for any insights you can offer.

Cheers

**Comment by pixelglow** [comment]
When the library opens a zip file, it performs several sanity checks that get lumped under `ZZEndOfCentralDirectoryReadErrorCode` at *ZZArchive.mm:124-139*:

* EOCD signature present in last 64K of the file.
* Zip file is a single disk zip file. ZipZap cannot handle multi-disk zip files.
* Start of central directory (as stated by the EOCD record) is before the end of central directory (as found by the signature) and has enough space for the given entries (as stated by the EOCD record).
* End of central directory record (as found by the signature) occurs at the actual end of the zip i.e. there's no spare bytes after the end or missing bytes before the end.

If you need to figure out which one is tripping the sanity check, put a breakpoint in the code and it should come up. In particular, I've seen a few zip files with extra bytes after the end which trip this error.

**Comment by atetlaw** [comment]
Hi @pixelglow , 
If this error is returned, when attempting to create a zip file from a directory, does it indicate something different?

Thanks,
Andrew

**Comment by pixelglow** [comment]
@atetlaw, if you create or update a zip file, the library does attempt to re-read the directory structures again so that could indicate a corrupted zip file or some bad write by the library code. If you can reproduce the error, would appreciate a minimal Xcode project showing the error.

**Comment by josh-fuggle** [comment]
@pixelglow We have recently upgraded from ZipZap version 8.0.4 to 8.1.1. Have there been any changes that could result in zipping issues?

**Comment by pixelglow** [comment]
@josh-fuggle: you can try looking through [the compare view](https://github.com/pixelglow/ZipZap/compare/8.0.4...8.1.1). We do have a commit that emits a `ZZCentralFileHeaderReadErrorCode` but not a `ZZEndOfCentralDirectoryReadErrorCode`. Does your existing code work correctly with 8.0.4?

**Comment by josh-fuggle** [comment]
We haven't seen any reports of this particular issue before, now we have reports from 4 separate devices. All on recent versions of our app.

**Comment by atetlaw** [comment]
Thanks for your help @pixelglow, @josh-fuggle is now working out a way to get the customer data off their device. Hopefully we'll discover the cause and then we may be able to make a test case.

Will let you know what we find.

**Comment by pixelglow** [comment]
It's been 2 months since the last message, so I'm considering this issue closed.
