### ISSUE TITLE
ZipZap iOS framework, objective-c, how can I make a single zip file, jpg s all under the Documents folder?

### ISSUE THREAD

**Issue by AxellH** [pixelglow/ZipZap#140]
ZipZap iOS framework, objective-c, how can I make a single zip file, jpg s all under the Documents folder?

My Documents directory : Documents directory: ( "1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg" )

**Comment by pixelglow** [comment]
Follow the recipe here: https://github.com/pixelglow/ZipZap/wiki/Recipes -- in particular, use `[NSData dataWithContentsOfFile:options:error:]` to get the data from each picture.
