### ISSUE TITLE
Compilation error on "Release" configuration

### ISSUE THREAD

**Issue by gmeroz** [pixelglow/zipzap#31]
Hi,

I was able to run my app with zipzap on Development mode, but when I try to archive for release it fails due to "'zipzap/zipzap.h' file not found"

Any ideas?

Gil

**Comment by Milanus** [comment]
Hello I have the same issue. When I run the debug version its ok, but when I try to make archive file not found error. Build Settings > Search Paths > Header Search Paths are set for the same (release and debug).  ../ZipZap. I have xcode 8.
