### ISSUE TITLE
Use of zipzap CocoaPod disables exception support project-wide

### ISSUE THREAD

**Issue by zygoat** [pixelglow/zipzap#78]
As described in some of the comments on #71, the mere inclusion of the zipzap CocoaPod in a project seems to have the effect of turning off support for Objective-C exceptions on a project-wide basis. For existing code and dependencies that are not easily altered, this is a blocker.

Earlier, I addressed the problem by ensuring a project-level setting was in force for `GCC_ENABLE_OBJC_EXCEPTIONS = YES`. After updating to CocoaPods 0.34.1 today and ensuring that a complete list of `link_with` targets are specified in my Podfile, this no longer works—the setting is superseded project-wide by zipzap.

As a further work-around, I moved this build setting to target-level on all affected targets in the project. While this now allows a build, it first creates a ton of spew when `pod install` is run:

```
[!] The `Kashoo [Development]` target overrides the `GCC_ENABLE_OBJC_EXCEPTIONS` build setting defined in `Pods/Target Support Files/Pods/Pods.development.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

This message is repeated for every build configuration on every target (4 targets x 3 configurations = 12 warnings in my case).

**Comment by mmcdole** [comment]
@pixelglow is this still an issue?

**Comment by zygoat** [comment]
The fix was merged to master, but a new release version of zipzap has not yet been made since then. (I've been pointing explicitly to master in my Podfile for the time being.)

**Comment by pixelglow** [comment]
Apologies, folks. I was busy with [Instaviz 2.0](https://redmine.pixelglow.com/projects/instaviz) and my old MBP had grown flaky. I have a new MBP now and some free time, so I'll work on getting 8.0.2 an official pod spec soon.

**Comment by ttaranov** [comment]
Glen, btw, talking about instaviz - this url is broken on its website http://instaviz.com/get/

**Comment by pixelglow** [comment]
@ttaranov thanks for the heads up. I fixed the link.

**Comment by zygoat** [comment]
I added a comment on [this diff of the podspec|https://github.com/pixelglow/zipzap/commit/d0a33d6fd96c311b3010bf4b3e855a93e65280ee] made just prior to releasing 8.0.2, which once again breaks my build.

**Comment by combinatorial** [comment]
I updated to CocoaPods 0.38.0 and I am seeing the return of the "target overrides the `GCC_ENABLE_OBJC_EXCEPTIONS` build setting" warning

**Comment by rsanchezsaez** [comment]
And exceptions are disabled project-wide as well.

**Comment by zygoat** [comment]
Same here; 8.0.4 reintroduces this regression. This issue needs to be reopened.

**Comment by zygoat** [comment]
Ping? Should I file a new issue instead?
