### ISSUE TITLE
ZipZap crashes adding entry to zip

### ISSUE THREAD

**Issue by peterallday** [pixelglow/zipzap#85]
Hi,

I have the following code
    ZZArchiveEntry *entry = [ZZArchiveEntry archiveEntryWithFileName:name
                                                            compress:YES
                                                           dataBlock:^(NSError** error){
                                                               return fileData;
                                                           }];
    NSArray *entries = [zipFile entries];
    if (!entries)    {
        entries = [NSArray arrayWithObject:entry];
    }
    else{
        entries = [entries arrayByAddingObject:entry];
    }
    [zipFile updateEntries:entries error:nil];

On my devices (and many others) it works fine, but one person has sent in the following crash log (decoded as best I can)

0   libobjc.A.dylib                     0x2f731cb6 realizeClass(objc_class*) + 98
1   libobjc.A.dylib                     0x2f7304b9 _class_getNonMetaClass + 177
2   libobjc.A.dylib                     0x2f73505b lookUpImpOrForward + 251
3   libobjc.A.dylib                     0x2f734f57 _class_lookupMethodAndLoadCache3 + 35
4   libobjc.A.dylib                     0x2f73b1d9 _objc_msgSend_uncached + 25
5   Foundation                          0x22b9477b -[NSFileManager fileSystemRepresentationWithPath:] + 215
-[ZZFileChannel newOutput:]
-[ZZArchive updateEntries:error:]

As far as I can tell this is coming from the following line in newOutput

	int fileDescriptor =  open(_URL.path.fileSystemRepresentation,
							   O_WRONLY | O_CREAT,
							   S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH);

but I have no idea what may be wrong.
It may be related to their data, but until I have more understanding of what is going wrong I can't debug it further.  Please help.

Thanks
Peter

**Comment by pixelglow** [comment]
No further feedback.
