### ISSUE TITLE
JAR File

### ISSUE THREAD

**Issue by Tobisaninfo** [pixelglow/zipzap#89]
Hi,
I try to extract / open a jar file with zipzap but all folders are presented as a file as there filemode (33188). I think a jar is only a zip file with some metainf stuff. Do you have a solution for that issue.

**Comment by pixelglow** [comment]
I believe that jar files are just zip files. Please email me a sample jar file and I'll check the file modes (glen dot low at pixelglow dot com).

**Comment by pixelglow** [comment]
I had a look at the JAR file and strangely enough, the directory entries have 0 for non-MSDOS external attributes and also 0 for MS-DOS file attributes. Therefore besides looking at the `fileMode`, you should check that the filename ends with a `/` as well to see if it's a directory.

**Comment by Tobisaninfo** [comment]
I added this condition (fileName.hasSuffix"/") and it worked very well. Except in one situation. He never find the META-INF folder ant it's manifest file. I have a screenshot for you, so you can see it. I also take this Game of Life.jar that I mailed you last time. https://www.dropbox.com/s/94pgirydn5kaaek/Bildschirmfoto%202015-02-04%20um%2022.01.04.png?dl=0

**Comment by pixelglow** [comment]
You don't have to have the intermediate directory entry `META-INF` in order to have the file entry `META-INF/MANIFEST.MF`. See https://github.com/pixelglow/zipzap/wiki/Recipes for guidance.
