### ISSUE TITLE
Folder error

### ISSUE THREAD

**Issue by Tobisaninfo** [pixelglow/zipzap#90]
I try to add my own filder to a zzarchive by creating a zzarchiventry like this: ZZArchiveEntry(directoryName: itemPath). That worked fine and your api detact this as a folder. But then I open the zip file with mac os x's Archive Utility or look inside with windows this new folder is presented as an empty file. The fileMode is also correct (16877 -> should be a folder). Do you have an idear how to fix that. I put my sample zip archive on dropbox, so you can download it.

https://www.dropbox.com/s/8m6bmqitliw74s2/Archiv.zip?dl=0

**Comment by pixelglow** [comment]
Your best bet is to append a `/` to the end of the directory name when saving it. This should keep Mac OS X happy and looks to be the convention for archiving directories.

Please see if this fix also keeps Windows happy -- it may be that Windows looks for the MS-DOS bits as well; if so I have some code changes to make.

**Comment by Tobisaninfo** [comment]
Thank you it worked fine. By the way I have no idear why this "/" is required.
