### ISSUE TITLE
Save as new zipfile

### ISSUE THREAD

**Issue by Tobisaninfo** [pixelglow/zipzap#91]
Hi, 
I have an other question or issue.
I have a document based app and in the save methode (writeToURL...) I create a new ZZArchive. But I have existing ZZArchiveEntries from reading the file. When I try to save that old entries to the new archive my program crashs. I it possible to "copy" that entries. But I think I have no better solution, because I cannot extract any archive, just to edit one element.
(If you know the java zip api ( nio) you should understand my issue.)

**Comment by pixelglow** [comment]
Typically to update a zip file, you would:
* open a `ZZArchive` with the file URL.
* copy the `entries` into `NSMutableArray`.
* update the copy appropriately e.g. by inserting an new entry at the right spot.
* use `updateEntries:error:` to update the archive.

See https://github.com/pixelglow/zipzap/wiki/Recipes for an example.

This is pretty efficient, the copy doesn't touch the file system and the `updateEntries:error:` will intelligently skip writing entries it knows are unchanged.

If you experience any crashes, do reply with the crashing code.

**Comment by Tobisaninfo** [comment]
I rewrite my app a little bit and final get this error:

2015-02-04 01:25:04.006 ZipEditor[8086:287615] *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
2015-02-04 01:25:04.009 ZipEditor[8086:287615] (
	0   CoreFoundation                      0x00007fff9081066c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8d9c776e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff906fda4f -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 383
	3   CoreFoundation                      0x00007fff907136cb +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	4   ZipEditor                           0x000000010002a603 -[ZZArchive updateEntries:error:] + 1971
	5   ZipEditor                           0x0000000100002ace _TFC9ZipEditor7Archive4savefS0_FT_Sb + 1790
	6   ZipEditor                           0x000000010001f492 _TFC9ZipEditor8Document10dataOfTypefS0_FTSS5errorGVSs33AutoreleasingUnsafeMutablePointerGSqCSo7NSError___GSqCSo6NSData_ + 114
	7   ZipEditor                           0x000000010001f560 _TToFC9ZipEditor8Document10dataOfTypefS0_FTSS5errorGVSs33AutoreleasingUnsafeMutablePointerGSqCSo7NSError___GSqCSo6NSData_ + 80
	8   AppKit                              0x00007fff8e4f4e6f -[NSDocument writeToURL:ofType:error:] + 861
	9   AppKit                              0x00007fff8e4f7da3 -[NSDocument writeToURL:ofType:forSaveOperation:originalContentsURL:error:] + 494
	10  AppKit                              0x00007fff8e4f6d0b -[NSDocument _writeSafelyToURL:ofType:forSaveOperation:forceTemporaryDirectory:error:] + 850
	11  AppKit                              0x00007fff8e4f7a33 -[NSDocument _writeSafelyToURL:ofType:forSaveOperation:error:] + 28
	12  AppKit                              0x00007fff8e4f7ba1 -[NSDocument writeSafelyToURL:ofType:forSaveOperation:error:] + 357
	13  AppKit                              0x00007fff8e504e85 __66-[NSDocument saveToURL:ofType:forSaveOperation:completionHandler:]_block_invoke_22312 + 240
	14  AppKit                              0x00007fff8e504d86 __66-[NSDocument saveToURL:ofType:forSaveOperation:completionHandler:]_block_invoke2309 + 365
	15  AppKit                              0x00007fff8e503186 __66-[NSDocument saveToURL:ofType:forSaveOperation:completionHandler:]_block_invoke2181 + 1587
	16  AppKit                              0x00007fff8e4ee6a9 -[NSDocument continueFileAccessUsingBlock:] + 222
	17  AppKit                              0x00007fff8e4fe5d4 __101-[NSDocument _fileCoordinator:asynchronouslyCoordinateReadingContentsAndWritingItemAtURL:byAccessor:]_block_invoke_2 + 137
	18  AppKit                              0x00007fff8e542df2 __62-[NSDocumentController(NSInternal) _onMainThreadInvokeWorker:]_block_invoke1918 + 175
	19  CoreFoundation                      0x00007fff9072e56c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	20  CoreFoundation                      0x00007fff90720675 __CFRunLoopDoBlocks + 341
	21  CoreFoundation                      0x00007fff907201b6 __CFRunLoopRun + 1814
	22  CoreFoundation                      0x00007fff9071f858 CFRunLoopRunSpecific + 296
	23  HIToolbox                           0x00007fff8dddeaef RunCurrentEventLoopInMode + 235
	24  HIToolbox                           0x00007fff8ddde86a ReceiveNextEventCommon + 431
	25  HIToolbox                           0x00007fff8ddde6ab _BlockUntilNextEventMatchingListInModeWithFilter + 71
	26  AppKit                              0x00007fff8e0d8f81 _DPSNextEvent + 964
	27  AppKit                              0x00007fff8e0d8730 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194
	28  AppKit                              0x00007fff8e0cc593 -[NSApplication run] + 594
	29  AppKit                              0x00007fff8e0b7a14 NSApplicationMain + 1832
	30  ZipEditor                           0x0000000100018f72 top_level_code + 34
	31  ZipEditor                           0x0000000100018faa main + 42
	32  libdyld.dylib                       0x00007fff8ac4e5c9 start + 1
)

**Comment by Tobisaninfo** [comment]
I'm so sorry but tha's not the only thing here:
2015-02-04 01:34:22.423 ZipEditor[8471:294462] -[OS_dispatch_data setData:]: unrecognized selector sent to instance 0x608000866280
2015-02-04 01:34:22.423 ZipEditor[8471:294462] -[OS_dispatch_data setData:]: unrecognized selector sent to instance 0x608000866280
2015-02-04 01:34:22.426 ZipEditor[8471:294462] (
	0   CoreFoundation                      0x00007fff9081066c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8d9c776e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff908136dd -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff9075aaa4 ___forwarding___ + 1028
	4   CoreFoundation                      0x00007fff9075a618 _CF_forwarding_prep_0 + 120
	5   ZipEditor                           0x0000000100032659 -[ZZDataChannel replaceWithChannel:error:] + 121
	6   ZipEditor                           0x000000010002ada8 -[ZZArchive updateEntries:error:] + 4008
	7   ZipEditor                           0x0000000100002dff _TFC9ZipEditor7Archive4savefS0_FT_Sb + 1359
	8   ZipEditor                           0x00000001000202b2 _TFC9ZipEditor8Document10dataOfTypefS0_FTSS5errorGVSs33AutoreleasingUnsafeMutablePointerGSqCSo7NSError___GSqCSo6NSData_ + 114
	9   ZipEditor                           0x0000000100020380 _TToFC9ZipEditor8Document10dataOfTypefS0_FTSS5errorGVSs33AutoreleasingUnsafeMutablePointerGSqCSo7NSError___GSqCSo6NSData_ + 80
	10  AppKit                              0x00007fff8e4f4e6f -[NSDocument writeToURL:ofType:error:] + 861
	11  AppKit                              0x00007fff8e4f7da3 -[NSDocument writeToURL:ofType:forSaveOperation:originalContentsURL:error:] + 494
	12  AppKit                              0x00007fff8e4f6d0b -[NSDocument _writeSafelyToURL:ofType:forSaveOperation:forceTemporaryDirectory:error:] + 850
	13  AppKit                              0x00007fff8e4f7a33 -[NSDocument _writeSafelyToURL:ofType:forSaveOperation:error:] + 28
	14  AppKit                              0x00007fff8e4f7ba1 -[NSDocument writeSafelyToURL:ofType:forSaveOperation:error:] + 357
	15  AppKit                              0x00007fff8e504e85 __66-[NSDocument saveToURL:ofType:forSaveOperation:completionHandler:]_block_invoke_22312 + 240
	16  AppKit                              0x00007fff8e504d86 __66-[NSDocument saveToURL:ofType:forSaveOperation:completionHandler:]_block_invoke2309 + 365
	17  AppKit                              0x00007fff8e503186 __66-[NSDocument saveToURL:ofType:forSaveOperation:completionHandler:]_block_invoke2181 + 1587
	18  AppKit                              0x00007fff8e4ee6a9 -[NSDocument continueFileAccessUsingBlock:] + 222
	19  AppKit                              0x00007fff8e4fe5d4 __101-[NSDocument _fileCoordinator:asynchronouslyCoordinateReadingContentsAndWritingItemAtURL:byAccessor:]_block_invoke_2 + 137
	20  AppKit                              0x00007fff8e542df2 __62-[NSDocumentController(NSInternal) _onMainThreadInvokeWorker:]_block_invoke1918 + 175
	21  CoreFoundation                      0x00007fff9072e56c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	22  CoreFoundation                      0x00007fff90720675 __CFRunLoopDoBlocks + 341
	23  CoreFoundation                      0x00007fff907201b6 __CFRunLoopRun + 1814
	24  CoreFoundation                      0x00007fff9071f858 CFRunLoopRunSpecific + 296
	25  HIToolbox                           0x00007fff8dddeaef RunCurrentEventLoopInMode + 235
	26  HIToolbox                           0x00007fff8ddde86a ReceiveNextEventCommon + 431
	27  HIToolbox                           0x00007fff8ddde6ab _BlockUntilNextEventMatchingListInModeWithFilter + 71
	28  AppKit                              0x00007fff8e0d8f81 _DPSNextEvent + 964
	29  AppKit                              0x00007fff8e0d8730 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 194
	30  AppKit                              0x00007fff8e0cc593 -[NSApplication run] + 594
	31  AppKit                              0x00007fff8e0b7a14 NSApplicationMain + 1832
	32  ZipEditor                           0x0000000100019d92 top_level_code + 34
	33  ZipEditor                           0x0000000100019dca main + 42
	34  libdyld.dylib                       0x00007fff8ac4e5c9 start + 1
)

**Comment by Tobisaninfo** [comment]
If you read my deleted answers yet forget about all of this, I used a NSData instead of NSMutableData (I forget a "self." in front of it).
