### ISSUE TITLE
Sample code for encryption

### ISSUE THREAD

**Issue by josipbernat** [pixelglow/zipzap#93]
Hi guys,

First of all great job with zipzap! I'm trying to make encrypted .zip archive but I can't figure out how to make it. Also I would like to stream file with NSInputStream / NSOutputStream to avoid memory problems. Now I'm doing it in this way:

+ (NSURL *)archiveWithFilePath:(NSString *)filePath encodingKey:(NSString *)key error:(NSError __autoreleasing **)error {

    NSDictionary *options =  @{ZZOpenOptionsCreateIfMissingKey: @YES,
                               ZZOpenOptionsEncodingKey: @(NSUTF8StringEncoding)};
    
    NSError *archiveError = nil;
    NSString *newArchivePath = [self __newArchiveFilePath];
    ZZArchive *archive = [[ZZArchive alloc] initWithURL:[NSURL fileURLWithPath:newArchivePath]
                                                options:options
                                                  error:&archiveError];
    if (archiveError) {
        *error = archiveError;
        return nil;
    }
    
    ZZArchiveEntry *newEntry = [ZZArchiveEntry archiveEntryWithFileName:[filePath lastPathComponent]
                                                               compress:YES
                                                              dataBlock:^NSData *(NSError *__autoreleasing *error) {
                                                    
                                                                  
                                                                  return [NSData dataWithContentsOfFile:filePath];
                                                              }];
    
    NSError *updateError = nil;
    [archive updateEntries:@[newEntry] error:&updateError];
    
    if (updateError) {
        *error = updateError;
        return nil;
    }
    
    return [NSURL fileURLWithPath:newArchivePath];
}

**Comment by pixelglow** [comment]
At the moment, zipzap doesn't support encrypting an archive, it only supports decrypting an archive.

If you want to stream, take a look at the `-[ZZZipNewTests checkCreatingZipEntriesWithSreamCompressed:chunkSize]` (line 59), which illustrates streaming into a zip entry from a data. The essential task is to break up your incoming data into chunks then use `-[NSOutputStream write:maxLength:]` to write out each chunk, and handle errors appropriately.

Hope that helps.

**Comment by josipbernat** [comment]
Hi,

I realized my self that zipzap doesn't support encryption for now. Unfortunately.
Thanks for sample code and I hope encryption will be here one day :)
