### ISSUE TITLE
Trying to write multiple images, result is unreadable images

### ISSUE THREAD

**Issue by dangalg** [pixelglow/zipzap#97]
my code is:

 NSString *zipFolderPath = [SF:@"%@/%@", NSTemporaryDirectory(), zipFolderName];

    ZZArchive* newArchive = [[ZZArchive alloc] initWithURL:[NSURL fileURLWithPath:zipFolderPath]
                                                   options:@{ZZOpenOptionsCreateIfMissingKey : @YES}
                                                     error:nil];
    
    NSString *filePath = [NSTemporaryDirectory() stringByAppendingPathComponent:[SF:@"%@/%@%d%@",pathToImagesFolder, imageFileName, 1, imageExt]];

[newArchive updateEntries:
         @[
           [ZZArchiveEntry archiveEntryWithFileName:filePath
                                           compress:YES
                                          dataBlock:^(NSError** error)
            {
                return [@"hello, world" dataUsingEncoding:NSUTF8StringEncoding];
            }]
           ]
                            error:nil];
        for (int i = 2; i < self.totalImages; i++) {
            filePath = [NSTemporaryDirectory() stringByAppendingPathComponent:[SF:@"%@/%@%d%@",pathToImagesFolder, imageFileName, i, imageExt]];
         
                ZZArchive* oldArchive = [ZZArchive archiveWithURL:[NSURL fileURLWithPath:zipFolderPath]
                                                            error:nil];
                [oldArchive updateEntries:
                 [oldArchive.entries arrayByAddingObject:
                  [ZZArchiveEntry archiveEntryWithFileName:filePath
                                                  compress:YES
                                                 dataBlock:^(NSError** error)
                   {
                       return [@"bye, world" dataUsingEncoding:NSUTF8StringEncoding];
                   }]]
                                    error:nil];
        }

**Comment by pixelglow** [comment]
`-[ZZArchiveEntry archiveEntryWithFileName:compress:dataBlock:]` and friends do not automatically read and compress the file; you actually have to open the file within the block and return the data.

**Comment by dangalg** [comment]
I am a noob to ios and objective c. as a noob I say the documentation is extremely unclear...
thanks for the answer.
for other noobs like me:
in the dataBlock you need to return the NSData of the object if the object is something like an image:

[newArchive updateEntries:
             @[
               [ZZArchiveEntry archiveEntryWithFileName:filename
                                               compress:YES
                                              dataBlock:^(NSError** error)
                {
                    // return the data of the image
                    NSData *data = [[NSFileManager defaultManager] contentsAtPath:filePath];
                    return data;
                }]
               ]
             error:nil];

Tell me, what happens if the image was a very large image say a giga, wouldn't the app crash when loading a giga to memory through NSData?

**Comment by pixelglow** [comment]
If your image is up to around 700MB, you can memory-map the file with minimal issues.

    NSData* data = [NSData dataWithContentsOfFile:filePath options:NSDataReadingMappedIfSafe error:&err];

This method doesn't actually consume all 700MB of memory in one go -- the system will only page in what's immediately necessary and drop parts of the map that aren't used.

For images > 700MB, I would recommend using the `streamBlock:` variation of archive entry instead. Search for `streamBlock:` in the test code for an example.

**Comment by dangalg** [comment]
thanks for the help and quick replies. please consider fixing the documentation with more real life examples. especially of multiple file zipping and directory zipping.
Or maybe make a -(void)zipDirectory:(NSString *)directoryPath;
Anyway thanks... You are awesome for making this
